### ISSUE TITLE
New Linux builds missing?

### ISSUE THREAD

**Issue by astrofrog** [conda-forge/mpich-feedstock#4]
It looks like only the first Linux build was successfully uploaded:

https://anaconda.org/conda-forge/mpich/files

Is this normal?

**Comment by ocefpaf** [comment]
> Is this normal?

Nope. But it did happen in some cases :unamused:

I had a similar issues with `nco` and it is due to a new tested I add. Commenting that test out solved it (actually I run the test only on OS X now). I will take a look here once I get back in the office.

**Comment by dalcinl** [comment]
@ocefpaf The latest build is also missing. I have no idea what's going one or where to look.

**Comment by ocefpaf** [comment]
I see the `OS X` packges and the CI for Linux did pass (https://circleci.com/gh/conda-forge/mpich-feedstock/41) :unamused: 

We do have some odd issue of CircleCI not uploading files when certain things happen in the build script. The only way to debug this is to abuse a bad practice.

1. clone the repo (not a fork);
2. edit the build and/or tests script by not running some parts we can live with, like tests;
3. commit that directly to master and check if that fixes the upload.

Here is a similar case where I only run those tests on `OS X` because they prevent the upload on Linux:

https://github.com/conda-forge/nco-feedstock/blob/master/recipe/run_test.sh#L12-L18

**Comment by jakirkham** [comment]
Looks like the most recent one is up.

**Comment by minrk** [comment]
latest build has both linux and mac
