### ISSUE TITLE
Add support for Windows

### ISSUE THREAD

**Issue by astrofrog** [conda-forge/mpich-feedstock#5]
MPICH should work on Windows, so it would be nice to add this here

**Comment by dalcinl** [comment]
@astrofrog AFAICT, MPICH does not work on Windows. Microsoft MPI is a MPICH derivative, but it is a different beast. Of course, we should add an ``msmpi`` package, though it should be kind of a metapackage, as it has to be installed in the system rather than in an environment. Unless I'm wrong and you know how to build MPICH on Windows, I think we should close this issue.
